version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: nothingtime:v0.1
    ports:
      - "5000:5000"
    environment:
      - DB_USERNAME=${{ secrets.DB_USERNAME }}
      - DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      - DB_HOST=${{ secrets.DB_HOST }}
      - DB_PORT=${{ secrets.DB_PORT }}
      - DB_NAME=${{ secrets.DB_NAME }}
    volumes:
      - .:/app
